add infinity water cell
GTNewHorizons/AE2FluidCraft-Rework pull request #212
Opened 2024-06-19 13:30 UTC by Quetz4l

infinity water cell from this PR https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/189

default recipe: 
![image](https://github.com/GTNewHorizons/AE2FluidCraft-Rework/assets/17906427/9df2f8c1-1505-4d1a-aff6-5b0a375bf678)

It provides infinite water and voids water if its priority is the same or higher than other disks.
![image](https://github.com/GTNewHorizons/AE2FluidCraft-Rework/assets/17906427/36a235f7-2991-4dcf-abe3-7cdbb9b2a793)

2024-06-19 13:32 UTC, boubou19 commented
i have nothing against this but why would someone uses this over a water hatch?

2024-06-19 13:41 UTC, Quetz4l commented
Water hatches are used for crafting on the go (when one craft is always being made) or a water hatch + input fluid bus / TFFT + water hatch for obtaining water for further orders through the ME system.

I currently have a very high water consumption at the UXV tier, so I have to keep the TFFT just for water, as I have all other fluids on disks. I want to get rid of the TFFT and the complicated methods of obtaining water since there are no proper ways to do it.

2024-06-19 21:20 UTC, glowredman commented
> i have nothing against this but why would someone uses this over a water hatch?

This is also nice in a non-GT context

2024-06-30 06:36 UTC, MCTBL commented
https://github.com/GTNewHorizons/AE2FluidCraft-Rework/assets/30978504/07e8ebbc-e6d9-4574-99c9-d82bac701291

2024-06-30 06:36 UTC, MCTBL commented
when there has other water cell in network, crafting job will can not start.

2024-06-30 11:01 UTC, OneEyeMaker requested changes

2024-06-30 12:59 UTC, Quetz4l commented on src/main/java/com/glodblock/github/common/storage/CreativeFluidCellInventory.java
> +                    iaeFluidStack.setStackSize(Long.MAX_VALUE);
The generation per second is sufficient, but not enough to have Integer.MAX_VALUE of water in the ME system. Large orders require much more water

2024-06-30 13:40 UTC, OneEyeMaker commented on src/main/java/com/glodblock/github/common/storage/CreativeFluidCellInventory.java
> +                    iaeFluidStack.setStackSize(Long.MAX_VALUE);
If so, there should be another PR (probably for both AE2 and AE2FC mods) that addresses the issue of handling infinite storage. And only after such PR(s) this change can be applied without problems.

2024-06-30 15:38 UTC, MCTBL commented on src/main/java/com/glodblock/github/common/storage/CreativeFluidCellInventory.java
> +                    iaeFluidStack.setStackSize(Long.MAX_VALUE);
ae is not good at handling infinite storage for now😂

2024-06-30 17:28 UTC, Quetz4l commented on src/main/java/com/glodblock/github/common/storage/CreativeFluidCellInventory.java
> +                    iaeFluidStack.setStackSize(Long.MAX_VALUE);
Returned to `Integer.MAX_VALUE`, need to increase the volume of infinite cells in a separate pr

2024-07-01 19:59 UTC, OneEyeMaker approved these changes

2024-07-01 22:15 UTC, merged