Fixed essentia level maintaining
GTNewHorizons/AE2FluidCraft-Rework pull request #245
Opened 2024-11-19 19:26 UTC by RecursivePineapple

You could previously level maintain the thaumic energistics fake essentia item, but this wouldn't work properly due to the continuous buildup of the fake items. It would work initially, but once you added or removed any essentia, it would not make more.

To fix this, this commit checks if the maintained item is an essentia stack and does two things.

First, it will convert NEI addon aspects to thaumic energistics. This is because it's very difficult to get the thaumic energistics item (to configure maintainers).
Side note: I tried to add some logic to AE's SlotFake that converts addon aspects to thaumic energistics aspects, but it broke level maintainers. It added very little, so I scrapped that idea and just made level maintainers treat the two fake essentia items the same.

Second, it will check the essentia cache to get the stack size instead of the item cache. Since essentia exists in its own cache, you cannot check the item cache to find its stored quantity. It would also be possible to check the fluid cache, but there wasn't much point since it was trivial to access the essentia cache instead.
The thaumic energistics item aspect is still needed to craft the essentia, so we only need to get the essentia stack size.

2024-11-19 19:27 UTC, RecursivePineapple commented
![2024-11-19_14 11 20](https://github.com/user-attachments/assets/f2baa530-97dc-43a2-9378-ac696d8c5e73)
![2024-11-19_14 11 26](https://github.com/user-attachments/assets/de151d77-b942-4c5c-8c5e-4ae949440164)
![2024-11-19_14 11 27](https://github.com/user-attachments/assets/18531aac-1bff-490f-85b0-bbc77dabf608)
![2024-11-19_14 11 29](https://github.com/user-attachments/assets/31e7be5e-353e-40da-9e9b-97338f313ece)
![2024-11-19_14 11 49](https://github.com/user-attachments/assets/a5d1f463-0d6f-4f7a-8889-47909799d9b6)
![2024-11-19_14 11 55](https://github.com/user-attachments/assets/0c3956d2-48a6-471a-9f4b-4d6d386fecd7)
![2024-11-19_14 16 46](https://github.com/user-attachments/assets/ac93abe2-3754-4413-9140-4efcd6079b5a)

2025-01-09 11:04 UTC, OneEyeMaker requested changes

2025-01-09 11:04 UTC, OneEyeMaker commented on src/main/java/com/glodblock/github/crossmod/thaumcraft/ThaumicEnergisticsCrafting.java
> +public class ThaumicEnergisticsCrafting {
My suggestion about organization of this class:
```
// pseudo-code
// public methods can be represented this way
public static IAEItemStack convertAspectStack(IAEItemStack stack) {
    if (ModAndClassUtil.ThE) {
        return convertAspectStackImpl(stack);
    }
    return stack; // default value
}

@Method(...)
private static IAEItemStack convertAspectStackImpl(IAEItemStack stack) {
    // and here you can any methods safely
}
```

2025-01-09 11:04 UTC, OneEyeMaker commented on src/main/java/com/glodblock/github/crossmod/thaumcraft/ThaumicEnergisticsCrafting.java
> +            return aspect;
Is there way to retrieve aspect without manual NBT manipulation? (Just asking)

2025-01-11 23:08 UTC, chochem commented on src/main/java/com/glodblock/github/common/tile/TileLevelMaintainer.java
> +                    if (ThaumicEnergisticsCrafting.isAspectStack(craftItem.getItemStack())) {
see https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/259

2025-01-12 17:24 UTC, RecursivePineapple commented on src/main/java/com/glodblock/github/crossmod/thaumcraft/ThaumicEnergisticsCrafting.java
> +            return aspect;
It looks like I would have to add a curse maven dep for it and then decompile it to figure out what methods are available. I figured the tc addon isn't going to change any time soon so it'd be fine to dig into the internals.

2025-01-14 10:15 UTC, merged